FROM heroku/heroku:18-build

LABEL   io.brasil="Brasil IO" \
        io.brasil.cli="foo" \
        version="0.1" \
        description="Imagem do Brasil.io para executar os código de extração de dados." \
        maintainer="luiz@thenets.org"

# TODO